#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Researcher\'s portal")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Insertadmin(admin instance);
  partial void Updateadmin(admin instance);
  partial void Deleteadmin(admin instance);
  partial void Insertcategory(category instance);
  partial void Updatecategory(category instance);
  partial void Deletecategory(category instance);
  partial void Insertauthor(author instance);
  partial void Updateauthor(author instance);
  partial void Deleteauthor(author instance);
  partial void Insertindex(index instance);
  partial void Updateindex(index instance);
  partial void Deleteindex(index instance);
  partial void InsertJournal(Journal instance);
  partial void UpdateJournal(Journal instance);
  partial void DeleteJournal(Journal instance);
  partial void Insertresearch_paper(research_paper instance);
  partial void Updateresearch_paper(research_paper instance);
  partial void Deleteresearch_paper(research_paper instance);
  partial void Insertuser(user instance);
  partial void Updateuser(user instance);
  partial void Deleteuser(user instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Researcher_s_portalConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<admin> admins
	{
		get
		{
			return this.GetTable<admin>();
		}
	}
	
	public System.Data.Linq.Table<category> categories
	{
		get
		{
			return this.GetTable<category>();
		}
	}
	
	public System.Data.Linq.Table<author> authors
	{
		get
		{
			return this.GetTable<author>();
		}
	}
	
	public System.Data.Linq.Table<favourite_list> favourite_lists
	{
		get
		{
			return this.GetTable<favourite_list>();
		}
	}
	
	public System.Data.Linq.Table<index> indexes
	{
		get
		{
			return this.GetTable<index>();
		}
	}
	
	public System.Data.Linq.Table<Journal> Journals
	{
		get
		{
			return this.GetTable<Journal>();
		}
	}
	
	public System.Data.Linq.Table<journal_index> journal_indexes
	{
		get
		{
			return this.GetTable<journal_index>();
		}
	}
	
	public System.Data.Linq.Table<research_paper> research_papers
	{
		get
		{
			return this.GetTable<research_paper>();
		}
	}
	
	public System.Data.Linq.Table<research_paper_author> research_paper_authors
	{
		get
		{
			return this.GetTable<research_paper_author>();
		}
	}
	
	public System.Data.Linq.Table<user> users
	{
		get
		{
			return this.GetTable<user>();
		}
	}
	
	public System.Data.Linq.Table<subscription> subscriptions
	{
		get
		{
			return this.GetTable<subscription>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.admin")]
public partial class admin : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _ad_name;
	
	private int _ad_id;
	
	private string _ad_pass;
	
	private string _ad_email;
	
	private EntitySet<Journal> _Journals;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onad_nameChanging(string value);
    partial void Onad_nameChanged();
    partial void Onad_idChanging(int value);
    partial void Onad_idChanged();
    partial void Onad_passChanging(string value);
    partial void Onad_passChanged();
    partial void Onad_emailChanging(string value);
    partial void Onad_emailChanged();
    #endregion
	
	public admin()
	{
		this._Journals = new EntitySet<Journal>(new Action<Journal>(this.attach_Journals), new Action<Journal>(this.detach_Journals));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ad_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string ad_name
	{
		get
		{
			return this._ad_name;
		}
		set
		{
			if ((this._ad_name != value))
			{
				this.Onad_nameChanging(value);
				this.SendPropertyChanging();
				this._ad_name = value;
				this.SendPropertyChanged("ad_name");
				this.Onad_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ad_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ad_id
	{
		get
		{
			return this._ad_id;
		}
		set
		{
			if ((this._ad_id != value))
			{
				this.Onad_idChanging(value);
				this.SendPropertyChanging();
				this._ad_id = value;
				this.SendPropertyChanged("ad_id");
				this.Onad_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ad_pass", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string ad_pass
	{
		get
		{
			return this._ad_pass;
		}
		set
		{
			if ((this._ad_pass != value))
			{
				this.Onad_passChanging(value);
				this.SendPropertyChanging();
				this._ad_pass = value;
				this.SendPropertyChanged("ad_pass");
				this.Onad_passChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ad_email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string ad_email
	{
		get
		{
			return this._ad_email;
		}
		set
		{
			if ((this._ad_email != value))
			{
				this.Onad_emailChanging(value);
				this.SendPropertyChanging();
				this._ad_email = value;
				this.SendPropertyChanged("ad_email");
				this.Onad_emailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="admin_Journal", Storage="_Journals", ThisKey="ad_id", OtherKey="ad_id")]
	public EntitySet<Journal> Journals
	{
		get
		{
			return this._Journals;
		}
		set
		{
			this._Journals.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_Journals(Journal entity)
	{
		this.SendPropertyChanging();
		entity.admin = this;
	}
	
	private void detach_Journals(Journal entity)
	{
		this.SendPropertyChanging();
		entity.admin = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.category")]
public partial class category : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _c_id;
	
	private string _c_name;
	
	private EntitySet<Journal> _Journals;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onc_idChanging(int value);
    partial void Onc_idChanged();
    partial void Onc_nameChanging(string value);
    partial void Onc_nameChanged();
    #endregion
	
	public category()
	{
		this._Journals = new EntitySet<Journal>(new Action<Journal>(this.attach_Journals), new Action<Journal>(this.detach_Journals));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int c_id
	{
		get
		{
			return this._c_id;
		}
		set
		{
			if ((this._c_id != value))
			{
				this.Onc_idChanging(value);
				this.SendPropertyChanging();
				this._c_id = value;
				this.SendPropertyChanged("c_id");
				this.Onc_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string c_name
	{
		get
		{
			return this._c_name;
		}
		set
		{
			if ((this._c_name != value))
			{
				this.Onc_nameChanging(value);
				this.SendPropertyChanging();
				this._c_name = value;
				this.SendPropertyChanged("c_name");
				this.Onc_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="category_Journal", Storage="_Journals", ThisKey="c_id", OtherKey="c_id")]
	public EntitySet<Journal> Journals
	{
		get
		{
			return this._Journals;
		}
		set
		{
			this._Journals.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_Journals(Journal entity)
	{
		this.SendPropertyChanging();
		entity.category = this;
	}
	
	private void detach_Journals(Journal entity)
	{
		this.SendPropertyChanging();
		entity.category = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.author")]
public partial class author : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _a_id;
	
	private string _a_name;
	
	private string _a_email;
	
	private string _a_country;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ona_idChanging(int value);
    partial void Ona_idChanged();
    partial void Ona_nameChanging(string value);
    partial void Ona_nameChanged();
    partial void Ona_emailChanging(string value);
    partial void Ona_emailChanged();
    partial void Ona_countryChanging(string value);
    partial void Ona_countryChanged();
    #endregion
	
	public author()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_a_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int a_id
	{
		get
		{
			return this._a_id;
		}
		set
		{
			if ((this._a_id != value))
			{
				this.Ona_idChanging(value);
				this.SendPropertyChanging();
				this._a_id = value;
				this.SendPropertyChanged("a_id");
				this.Ona_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_a_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string a_name
	{
		get
		{
			return this._a_name;
		}
		set
		{
			if ((this._a_name != value))
			{
				this.Ona_nameChanging(value);
				this.SendPropertyChanging();
				this._a_name = value;
				this.SendPropertyChanged("a_name");
				this.Ona_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_a_email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string a_email
	{
		get
		{
			return this._a_email;
		}
		set
		{
			if ((this._a_email != value))
			{
				this.Ona_emailChanging(value);
				this.SendPropertyChanging();
				this._a_email = value;
				this.SendPropertyChanged("a_email");
				this.Ona_emailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_a_country", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string a_country
	{
		get
		{
			return this._a_country;
		}
		set
		{
			if ((this._a_country != value))
			{
				this.Ona_countryChanging(value);
				this.SendPropertyChanging();
				this._a_country = value;
				this.SendPropertyChanged("a_country");
				this.Ona_countryChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.favourite_list")]
public partial class favourite_list
{
	
	private int _j_id;
	
	private int _u_id;
	
	public favourite_list()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j_id", DbType="Int NOT NULL")]
	public int j_id
	{
		get
		{
			return this._j_id;
		}
		set
		{
			if ((this._j_id != value))
			{
				this._j_id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_id", DbType="Int NOT NULL")]
	public int u_id
	{
		get
		{
			return this._u_id;
		}
		set
		{
			if ((this._u_id != value))
			{
				this._u_id = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[index]")]
public partial class index : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _index_id;
	
	private string _index_name;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onindex_idChanging(int value);
    partial void Onindex_idChanged();
    partial void Onindex_nameChanging(string value);
    partial void Onindex_nameChanged();
    #endregion
	
	public index()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_index_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int index_id
	{
		get
		{
			return this._index_id;
		}
		set
		{
			if ((this._index_id != value))
			{
				this.Onindex_idChanging(value);
				this.SendPropertyChanging();
				this._index_id = value;
				this.SendPropertyChanged("index_id");
				this.Onindex_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_index_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string index_name
	{
		get
		{
			return this._index_name;
		}
		set
		{
			if ((this._index_name != value))
			{
				this.Onindex_nameChanging(value);
				this.SendPropertyChanging();
				this._index_name = value;
				this.SendPropertyChanged("index_name");
				this.Onindex_nameChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Journal")]
public partial class Journal : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _j_id;
	
	private string _J_name;
	
	private string _Impact_factor;
	
	private string _citations;
	
	private int _YOP;
	
	private string _Publication_link;
	
	private int _index_id;
	
	private System.Nullable<int> _c_id;
	
	private System.Nullable<int> _ad_id;
	
	private EntitySet<research_paper> _research_papers;
	
	private EntityRef<admin> _admin;
	
	private EntityRef<category> _category;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onj_idChanging(int value);
    partial void Onj_idChanged();
    partial void OnJ_nameChanging(string value);
    partial void OnJ_nameChanged();
    partial void OnImpact_factorChanging(string value);
    partial void OnImpact_factorChanged();
    partial void OncitationsChanging(string value);
    partial void OncitationsChanged();
    partial void OnYOPChanging(int value);
    partial void OnYOPChanged();
    partial void OnPublication_linkChanging(string value);
    partial void OnPublication_linkChanged();
    partial void Onindex_idChanging(int value);
    partial void Onindex_idChanged();
    partial void Onc_idChanging(System.Nullable<int> value);
    partial void Onc_idChanged();
    partial void Onad_idChanging(System.Nullable<int> value);
    partial void Onad_idChanged();
    #endregion
	
	public Journal()
	{
		this._research_papers = new EntitySet<research_paper>(new Action<research_paper>(this.attach_research_papers), new Action<research_paper>(this.detach_research_papers));
		this._admin = default(EntityRef<admin>);
		this._category = default(EntityRef<category>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int j_id
	{
		get
		{
			return this._j_id;
		}
		set
		{
			if ((this._j_id != value))
			{
				this.Onj_idChanging(value);
				this.SendPropertyChanging();
				this._j_id = value;
				this.SendPropertyChanged("j_id");
				this.Onj_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_J_name", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
	public string J_name
	{
		get
		{
			return this._J_name;
		}
		set
		{
			if ((this._J_name != value))
			{
				this.OnJ_nameChanging(value);
				this.SendPropertyChanging();
				this._J_name = value;
				this.SendPropertyChanged("J_name");
				this.OnJ_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Impact_factor", DbType="NVarChar(50)")]
	public string Impact_factor
	{
		get
		{
			return this._Impact_factor;
		}
		set
		{
			if ((this._Impact_factor != value))
			{
				this.OnImpact_factorChanging(value);
				this.SendPropertyChanging();
				this._Impact_factor = value;
				this.SendPropertyChanged("Impact_factor");
				this.OnImpact_factorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_citations", DbType="NVarChar(50)")]
	public string citations
	{
		get
		{
			return this._citations;
		}
		set
		{
			if ((this._citations != value))
			{
				this.OncitationsChanging(value);
				this.SendPropertyChanging();
				this._citations = value;
				this.SendPropertyChanged("citations");
				this.OncitationsChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YOP", DbType="Int NOT NULL")]
	public int YOP
	{
		get
		{
			return this._YOP;
		}
		set
		{
			if ((this._YOP != value))
			{
				this.OnYOPChanging(value);
				this.SendPropertyChanging();
				this._YOP = value;
				this.SendPropertyChanged("YOP");
				this.OnYOPChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Publication_link", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
	public string Publication_link
	{
		get
		{
			return this._Publication_link;
		}
		set
		{
			if ((this._Publication_link != value))
			{
				this.OnPublication_linkChanging(value);
				this.SendPropertyChanging();
				this._Publication_link = value;
				this.SendPropertyChanged("Publication_link");
				this.OnPublication_linkChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_index_id", DbType="Int NOT NULL")]
	public int index_id
	{
		get
		{
			return this._index_id;
		}
		set
		{
			if ((this._index_id != value))
			{
				this.Onindex_idChanging(value);
				this.SendPropertyChanging();
				this._index_id = value;
				this.SendPropertyChanged("index_id");
				this.Onindex_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_id", DbType="Int")]
	public System.Nullable<int> c_id
	{
		get
		{
			return this._c_id;
		}
		set
		{
			if ((this._c_id != value))
			{
				if (this._category.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onc_idChanging(value);
				this.SendPropertyChanging();
				this._c_id = value;
				this.SendPropertyChanged("c_id");
				this.Onc_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ad_id", DbType="Int")]
	public System.Nullable<int> ad_id
	{
		get
		{
			return this._ad_id;
		}
		set
		{
			if ((this._ad_id != value))
			{
				if (this._admin.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onad_idChanging(value);
				this.SendPropertyChanging();
				this._ad_id = value;
				this.SendPropertyChanged("ad_id");
				this.Onad_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Journal_research_paper", Storage="_research_papers", ThisKey="j_id", OtherKey="j_id")]
	public EntitySet<research_paper> research_papers
	{
		get
		{
			return this._research_papers;
		}
		set
		{
			this._research_papers.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="admin_Journal", Storage="_admin", ThisKey="ad_id", OtherKey="ad_id", IsForeignKey=true)]
	public admin admin
	{
		get
		{
			return this._admin.Entity;
		}
		set
		{
			admin previousValue = this._admin.Entity;
			if (((previousValue != value) 
						|| (this._admin.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._admin.Entity = null;
					previousValue.Journals.Remove(this);
				}
				this._admin.Entity = value;
				if ((value != null))
				{
					value.Journals.Add(this);
					this._ad_id = value.ad_id;
				}
				else
				{
					this._ad_id = default(Nullable<int>);
				}
				this.SendPropertyChanged("admin");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="category_Journal", Storage="_category", ThisKey="c_id", OtherKey="c_id", IsForeignKey=true)]
	public category category
	{
		get
		{
			return this._category.Entity;
		}
		set
		{
			category previousValue = this._category.Entity;
			if (((previousValue != value) 
						|| (this._category.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._category.Entity = null;
					previousValue.Journals.Remove(this);
				}
				this._category.Entity = value;
				if ((value != null))
				{
					value.Journals.Add(this);
					this._c_id = value.c_id;
				}
				else
				{
					this._c_id = default(Nullable<int>);
				}
				this.SendPropertyChanged("category");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_research_papers(research_paper entity)
	{
		this.SendPropertyChanging();
		entity.Journal = this;
	}
	
	private void detach_research_papers(research_paper entity)
	{
		this.SendPropertyChanging();
		entity.Journal = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.journal_index")]
public partial class journal_index
{
	
	private int _j_id;
	
	private int _index_id;
	
	public journal_index()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j_id", DbType="Int NOT NULL")]
	public int j_id
	{
		get
		{
			return this._j_id;
		}
		set
		{
			if ((this._j_id != value))
			{
				this._j_id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_index_id", DbType="Int NOT NULL")]
	public int index_id
	{
		get
		{
			return this._index_id;
		}
		set
		{
			if ((this._index_id != value))
			{
				this._index_id = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.research_paper")]
public partial class research_paper : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _research_name;
	
	private int _r_id;
	
	private string _keywords;
	
	private string _title;
	
	private int _j_id;
	
	private string _abstract_view;
	
	private string _paper_upload;
	
	private EntityRef<Journal> _Journal;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onresearch_nameChanging(string value);
    partial void Onresearch_nameChanged();
    partial void Onr_idChanging(int value);
    partial void Onr_idChanged();
    partial void OnkeywordsChanging(string value);
    partial void OnkeywordsChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void Onj_idChanging(int value);
    partial void Onj_idChanged();
    partial void Onabstract_viewChanging(string value);
    partial void Onabstract_viewChanged();
    partial void Onpaper_uploadChanging(string value);
    partial void Onpaper_uploadChanged();
    #endregion
	
	public research_paper()
	{
		this._Journal = default(EntityRef<Journal>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_research_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string research_name
	{
		get
		{
			return this._research_name;
		}
		set
		{
			if ((this._research_name != value))
			{
				this.Onresearch_nameChanging(value);
				this.SendPropertyChanging();
				this._research_name = value;
				this.SendPropertyChanged("research_name");
				this.Onresearch_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_r_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int r_id
	{
		get
		{
			return this._r_id;
		}
		set
		{
			if ((this._r_id != value))
			{
				this.Onr_idChanging(value);
				this.SendPropertyChanging();
				this._r_id = value;
				this.SendPropertyChanged("r_id");
				this.Onr_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_keywords", DbType="Char(10) NOT NULL", CanBeNull=false)]
	public string keywords
	{
		get
		{
			return this._keywords;
		}
		set
		{
			if ((this._keywords != value))
			{
				this.OnkeywordsChanging(value);
				this.SendPropertyChanging();
				this._keywords = value;
				this.SendPropertyChanged("keywords");
				this.OnkeywordsChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string title
	{
		get
		{
			return this._title;
		}
		set
		{
			if ((this._title != value))
			{
				this.OntitleChanging(value);
				this.SendPropertyChanging();
				this._title = value;
				this.SendPropertyChanged("title");
				this.OntitleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j_id", DbType="Int NOT NULL")]
	public int j_id
	{
		get
		{
			return this._j_id;
		}
		set
		{
			if ((this._j_id != value))
			{
				if (this._Journal.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onj_idChanging(value);
				this.SendPropertyChanging();
				this._j_id = value;
				this.SendPropertyChanged("j_id");
				this.Onj_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_abstract_view", DbType="NVarChar(3000) NOT NULL", CanBeNull=false)]
	public string abstract_view
	{
		get
		{
			return this._abstract_view;
		}
		set
		{
			if ((this._abstract_view != value))
			{
				this.Onabstract_viewChanging(value);
				this.SendPropertyChanging();
				this._abstract_view = value;
				this.SendPropertyChanged("abstract_view");
				this.Onabstract_viewChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paper_upload", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string paper_upload
	{
		get
		{
			return this._paper_upload;
		}
		set
		{
			if ((this._paper_upload != value))
			{
				this.Onpaper_uploadChanging(value);
				this.SendPropertyChanging();
				this._paper_upload = value;
				this.SendPropertyChanged("paper_upload");
				this.Onpaper_uploadChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Journal_research_paper", Storage="_Journal", ThisKey="j_id", OtherKey="j_id", IsForeignKey=true)]
	public Journal Journal
	{
		get
		{
			return this._Journal.Entity;
		}
		set
		{
			Journal previousValue = this._Journal.Entity;
			if (((previousValue != value) 
						|| (this._Journal.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Journal.Entity = null;
					previousValue.research_papers.Remove(this);
				}
				this._Journal.Entity = value;
				if ((value != null))
				{
					value.research_papers.Add(this);
					this._j_id = value.j_id;
				}
				else
				{
					this._j_id = default(int);
				}
				this.SendPropertyChanged("Journal");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.research_paper_author")]
public partial class research_paper_author
{
	
	private int _a_id;
	
	private string _is_mainauthor;
	
	private int _r_id;
	
	public research_paper_author()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_a_id", DbType="Int NOT NULL")]
	public int a_id
	{
		get
		{
			return this._a_id;
		}
		set
		{
			if ((this._a_id != value))
			{
				this._a_id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_mainauthor", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string is_mainauthor
	{
		get
		{
			return this._is_mainauthor;
		}
		set
		{
			if ((this._is_mainauthor != value))
			{
				this._is_mainauthor = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_r_id", DbType="Int NOT NULL")]
	public int r_id
	{
		get
		{
			return this._r_id;
		}
		set
		{
			if ((this._r_id != value))
			{
				this._r_id = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[user]")]
public partial class user : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _u_id;
	
	private string _u_email;
	
	private int _a_id;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onu_idChanging(int value);
    partial void Onu_idChanged();
    partial void Onu_emailChanging(string value);
    partial void Onu_emailChanged();
    partial void Ona_idChanging(int value);
    partial void Ona_idChanged();
    #endregion
	
	public user()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int u_id
	{
		get
		{
			return this._u_id;
		}
		set
		{
			if ((this._u_id != value))
			{
				this.Onu_idChanging(value);
				this.SendPropertyChanging();
				this._u_id = value;
				this.SendPropertyChanged("u_id");
				this.Onu_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string u_email
	{
		get
		{
			return this._u_email;
		}
		set
		{
			if ((this._u_email != value))
			{
				this.Onu_emailChanging(value);
				this.SendPropertyChanging();
				this._u_email = value;
				this.SendPropertyChanged("u_email");
				this.Onu_emailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_a_id", DbType="Int NOT NULL")]
	public int a_id
	{
		get
		{
			return this._a_id;
		}
		set
		{
			if ((this._a_id != value))
			{
				this.Ona_idChanging(value);
				this.SendPropertyChanging();
				this._a_id = value;
				this.SendPropertyChanged("a_id");
				this.Ona_idChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.subscription")]
public partial class subscription
{
	
	private int _j_id;
	
	private int _u_id;
	
	public subscription()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j_id", DbType="Int NOT NULL")]
	public int j_id
	{
		get
		{
			return this._j_id;
		}
		set
		{
			if ((this._j_id != value))
			{
				this._j_id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_id", DbType="Int NOT NULL")]
	public int u_id
	{
		get
		{
			return this._u_id;
		}
		set
		{
			if ((this._u_id != value))
			{
				this._u_id = value;
			}
		}
	}
}
#pragma warning restore 1591
