<?xml version="1.0" encoding="utf-8"?><Database Name="Researcher's portal" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-3N40DTS\SQLEXPRESS;Initial Catalog=&quot;Researcher's portal&quot;;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Researcher_s_portalConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.admin" Member="admins">
    <Type Name="admin">
      <Column Name="ad_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ad_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ad_pass" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ad_email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="admin_Journal" Member="Journals" ThisKey="ad_id" OtherKey="ad_id" Type="Journal" />
    </Type>
  </Table>
  <Table Name="dbo.category" Member="categories">
    <Type Name="category">
      <Column Name="c_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="c_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="category_Journal" Member="Journals" ThisKey="c_id" OtherKey="c_id" Type="Journal" />
    </Type>
  </Table>
  <Table Name="dbo.author" Member="authors">
    <Type Name="author">
      <Column Name="a_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="a_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="a_email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="a_country" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="author_research_paper_author" Member="research_paper_authors" ThisKey="a_id" OtherKey="a_id" Type="research_paper_author" />
    </Type>
  </Table>
  <Table Name="dbo.favourite_list" Member="favourite_lists">
    <Type Name="favourite_list">
      <Column Name="j_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="u_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Journal_favourite_list" Member="Journal" ThisKey="j_id" OtherKey="j_id" Type="Journal" IsForeignKey="true" />
      <Association Name="user_favourite_list" Member="user" ThisKey="u_id" OtherKey="u_id" Type="user" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[index]" Member="indexes">
    <Type Name="index">
      <Column Name="index_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="index_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="index_journal_index" Member="journal_indexes" ThisKey="index_id" OtherKey="index_id" Type="journal_index" />
    </Type>
  </Table>
  <Table Name="dbo.Journal" Member="Journals">
    <Type Name="Journal">
      <Column Name="j_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="J_name" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Impact_factor" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="citations" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="YOP" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Publication_link" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="index_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="c_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ad_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Journal_favourite_list" Member="favourite_lists" ThisKey="j_id" OtherKey="j_id" Type="favourite_list" />
      <Association Name="Journal_journal_index" Member="journal_indexes" ThisKey="j_id" OtherKey="j_id" Type="journal_index" />
      <Association Name="Journal_research_paper" Member="research_papers" ThisKey="j_id" OtherKey="j_id" Type="research_paper" />
      <Association Name="Journal_subscription" Member="subscriptions" ThisKey="j_id" OtherKey="j_id" Type="subscription" />
      <Association Name="admin_Journal" Member="admin" ThisKey="ad_id" OtherKey="ad_id" Type="admin" IsForeignKey="true" />
      <Association Name="category_Journal" Member="category" ThisKey="c_id" OtherKey="c_id" Type="category" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.journal_index" Member="journal_indexes">
    <Type Name="journal_index">
      <Column Name="j_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="index_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="index_journal_index" Member="index" ThisKey="index_id" OtherKey="index_id" Type="index" IsForeignKey="true" />
      <Association Name="Journal_journal_index" Member="Journal" ThisKey="j_id" OtherKey="j_id" Type="Journal" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.research_paper" Member="research_papers">
    <Type Name="research_paper">
      <Column Name="research_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="r_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="keywords" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="j_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="abstract_view" Type="System.String" DbType="NVarChar(3000) NOT NULL" CanBeNull="false" />
      <Column Name="paper_upload" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="research_paper_research_paper_author" Member="research_paper_authors" ThisKey="r_id" OtherKey="r_id" Type="research_paper_author" />
      <Association Name="Journal_research_paper" Member="Journal" ThisKey="j_id" OtherKey="j_id" Type="Journal" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.research_paper_author" Member="research_paper_authors">
    <Type Name="research_paper_author">
      <Column Name="a_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="is_mainauthor" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="r_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="author_research_paper_author" Member="author" ThisKey="a_id" OtherKey="a_id" Type="author" IsForeignKey="true" />
      <Association Name="research_paper_research_paper_author" Member="research_paper" ThisKey="r_id" OtherKey="r_id" Type="research_paper" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[user]" Member="users">
    <Type Name="user">
      <Column Name="u_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="u_email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="a_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="user_favourite_list" Member="favourite_lists" ThisKey="u_id" OtherKey="u_id" Type="favourite_list" />
      <Association Name="user_subscription" Member="subscriptions" ThisKey="u_id" OtherKey="u_id" Type="subscription" />
    </Type>
  </Table>
  <Table Name="dbo.subscription" Member="subscriptions">
    <Type Name="subscription">
      <Column Name="j_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="u_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Journal_subscription" Member="Journal" ThisKey="j_id" OtherKey="j_id" Type="Journal" IsForeignKey="true" />
      <Association Name="user_subscription" Member="user" ThisKey="u_id" OtherKey="u_id" Type="user" IsForeignKey="true" />
    </Type>
  </Table>
</Database>